### PR TITLE
Initializing Payload

### PR DESCRIPTION
**Pull request by angelcambero**
Problem: Crashing when building the Payload for GET calls.
Fix: Initializing the Payload, initially is undefined.

### CODE REVIEW

**Comment by tflanagan** [comment]
Hmm, jsperf is down again so I can't test it, but can you move the initialization up to just before the if statement?

this.payload is a string regardless of POST vs GET.

**Comment by angelcambero** [comment]
I specified that is the for GET because basically to determine if you want to use GET or POST is by setting useXML to true/false.
When useXML is set to True then you use "this.payload = builder.buildObject(this.options);" to build the payload (it doesn't have to be pre-initialized. 
When you set useXML to false then we use GET and the payload is built different:  this.payload += '&' + arg + '=' + this.options[arg];   And it would crash because initially this.payload is undefined.

Yes you can move it before the if statement like this:
		this.payload = '';
		if(this.parent.settings.flags.useXML === true){  .....

However, I found something else, that I wanted to tell you about and it's regarding the XML format.
I don't know if I should open another pull request for that or just text you here.

**Comment by tflanagan** [comment]
I understood the issue, I'm thinking in regards of performance - I run 1000's of these requests a day.

What have you found in the format?

**Comment by angelcambero** [comment]
In performance I would keep it inside because you would only have to initialize it only when you need it. 

Regarding the XML format. If you try using POSTMAN or any other tool you would see that Quickbase accepts different XML format (depending on the type of action ? I'm not sure).

CREATING A NEW RECORD ( API_AddRecord )

//work
<qdbapi>
<field name="owner">angel cambero</field>
<field name="name">testName</field>
<field name="ami">12345</field>
<field name="ip">1.2.3.4</field>
<field name="url">www.angelcambero.com</field>
</qdbapi>

//doesn’t work
<qdbapi>
    <owner>angel cambero</owner>
    <name>testName</name>
    <ami>12345</ami>
    <ip>1.3.5.6</ip>
    <url>www.angelcambero.com</url>
</qdbapi>


LOGIN: (API_DoQuery)

//doesn’t work
<qdbapi>
    <field name="username">acamberooo</field>
    <field name="password”>xxxxxxxxx</field>
    <field name="apptoken">dkmiy9gdxkxieycxmwyijc4mubmj</field>
    <field name="includeRids">1</field>
    <field name="fmt">flat</field>
</qdbapi>

//works
<qdbapi>
    <username>acamberooo</username>
    <password>xxxxxxxxxx!</password>
    <apptoken>dkmiy9gdxkxieycxmwyijc4mubmj</apptoken>
    <fmt>flat</fmt>
</qdbapi>
 

So, what I did is to parse it differently when you use API_AddRecord, the actual this.payload = builder.buildObject(this.options); returns the format:
<qdbapi>
    <owner>MrTester</owner>
    <name>testName</name>
    <ami>12345</ami>
    <ip>1.3.5.6</ip>
    <url>www.angelcambero.com</url>
</qdbapi>

but I need this format:
<qdbapi>
<field name="owner">angel cambero</field>
<field name="name">testName</field>
<field name="ami">12345</field>
<field name="ip">1.2.3.4</field>
<field name="url">www.angelcambero.com</field>
</qdbapi>

**Comment by tflanagan** [comment]
Please enclose your XML in proper markdown format, I really can't discern what you're trying to show me.

**Comment by tflanagan** [comment]
This library does not build the XML.

For help on building your XML, please reference the xml2js module.

https://www.npmjs.com/package/xml2js
https://github.com/Leonidas-from-XIV/node-xml2js

---

As to the this.payload initialization, I've patched it in v0.3.4

**Comment by tflanagan** [comment]
Also, look at this function:

https://github.com/tflanagan/node-quickbase/blob/master/main.js#L509

**Comment by angelcambero** [comment]
I did check the library actually. 

I didn't find the option to generate XML like: <field name="car"> Toyota </field>
Instead of: <car> Toyota </car>

Quickbase is not working for the format <car> Toyota </car> when you try to Create a new record.

However, probably that works fine for more people and it's something internal. So I will just leave the problem that I had posted here and if any other person see it can contact me or reply in this thread.

**Comment by tflanagan** [comment]
I'm not able to reproduce the issue.

Here are two ways you can use API_AddRecord:

```javascript
quickbase.api('API_AddRecord', {
	dbid: '****',
	fields: [
		{ name: 'Action', value: 'test' }
	]
});
```

Will yield:
```xml
<qdbapi>
	<dbid>****</dbid>
	<msInUTC>1</msInUTC>
	<apptoken>****</apptoken>
	<ticket>****</ticket>
	<includeRids>1</includeRids>
	<fmt>structured</fmt>
	<field name="Action">test</field>
</qdbapi>
```

and then

```javascript
quickbase.api('API_AddRecord', {
	dbid: '****',
	fields: [
		{ fid: 9, value: 'test' }
	]
});
```

Will yield:
```xml
<qdbapi>
	<dbid>****</dbid>
	<msInUTC>1</msInUTC>
	<apptoken>****</apptoken>
	<ticket>****</ticket>
	<includeRids>1</includeRids>
	<fmt>structured</fmt>
	<field fid="9">test</field>
</qdbapi>
```

**Comment by angelcambero** [comment]
Nice!
I wasn't implementing node-quickbase properly.
I thought that it was going to parse as a field whatever that was inside of 'fields'.
But now I see that you have to specify with 'fid' and 'value'.

Remember to fix the Payload initialization.

**Comment by tflanagan** [comment]
It was addressed in the v0.3.4 release, thank you for finding that bug.

https://github.com/tflanagan/node-quickbase/commit/8c7bc9ae589da34e588594472ea6c8509084fb89

**Pull request closed without merging**
