### PR TITLE
Update main.js

### PR DESCRIPTION
**Pull request by angelcambero**
Problem: throwing Error when you try to authenticate. 
Cause: Comparison between String and Number.

### CODE REVIEW

**Comment by tflanagan** [comment]
Good catch, merging.

**Comment by angelcambero** [comment]
image

The output is : // string number

**Comment by tflanagan** [comment]
what version are you working with?

**Comment by angelcambero** [comment]
^0.3.2

**Comment by tflanagan** [comment]
Interesting, I'm getting number === number, none of my tests have been getting string === number.

What's the value of result.errcode?

**Comment by chetanddesai** [comment]
@tflanagan @angelcambero I'm happy to try it on my machine too, to get a third "works/doesn't work" on my machine

**Comment by tflanagan** [comment]
Can you send me the code - without credentials - you are using to execute the Authentication call and relevant code?

I'll use my realm/credentials

**Comment by tflanagan** [comment]
I've found the bug, patching now.

**Comment by angelcambero** [comment]
I think the problem is in the cleanXML function.
Here:
if(Math.abs(parseInt(value, radix)) <= Number.MAX_SAFE_INTEGER){
Use Number.MAX_VALUE instead of Number.MAX_SAFE_INTEGER.
Number.MAX_SAFE_INTEGER returns undefined.

**Comment by tflanagan** [comment]
Yes, that was the problem.

Linux distros of Nodejs do not have that property. It has been fixed in 0.3.3

**Comment by chetanddesai** [comment]
Thanks @tflanagan !!!

**Comment by angelcambero** [comment]
Thank you @tflanagan !  Nice job with this module.!!

**Comment by tflanagan** [comment]
Thanks! :)

**Pull request merged**
